### ISSUE TITLE
better command support?

### ISSUE THREAD

**Issue by chino** [chriseppstein/rbenv-each#14]
It would be nice to simply eval whatever is left on the command line.

For instance I'd love to do:

```
rbenv each -v gem list \| grep "a b"
```

With proper quoting support so that the grep in the example above works appropriately.

**Comment by mislav** [comment]
No, we're not going to do anything tricky like that. If you find yourself needing to do some shell functions/piping across rbenv versions, you could simply:

```sh
for v in `rbenv versions --bare`; do RBENV_VERSION=$v gem list | grep "a b"; done
```

**Comment by chino** [comment]
Yea, I just basically took that and change it to call `eval "$@"` and it seems to work great...

Would be cool if rbenv-each supported it.

**Comment by mislav** [comment]
I want to refrain from doing eval internally since that is not how I want people to use rbenv-each.

However you can always execute bash interpreter with any script that you want:

```
rbenv each bash -c 'gem list | grep "a b"'
```

**Comment by chino** [comment]
Hm, your right.  I forget off top of my head and I'm on road right now but
does rbenv support aliases?  It could be a simple handy alias.

**Comment by mislav** [comment]
rbenv doesn't support aliases but your shell does ;)

```
alias rbenv-each-eval='rbenv each bash -c'
```

**Comment by chino** [comment]
I agree.  However I do like git aliases even though they could just be
shell aliases  :)
